# Generated by Django 4.0 on 2021-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthapplication',
            table='oauthapplication',
        ),
    ]
